import { useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowLeft, BookOpen, ChevronRight, Command, Search, ShieldQuestion, Wrench, Zap } from "lucide-react";
import { trpc } from "@/lib/trpc";

const fallbackDocs = [{ slug: "pairing-guide", title: "Pair your WhatsApp number", category: "Getting started", excerpt: "Choose a bot, enter your number, and follow the code status tracker.", content: "Select a bot, enter your number in international format, and request a pairing code. Keep the bot worker online while the request is pending. When WhatsApp accepts the code, your dashboard will show Connected." }, { slug: "telegram-keys", title: "Generate and use a Telegram key", category: "Keys", excerpt: "Create a time-limited key for your selected bot.", content: "Choose a bot and duration, optionally add your Telegram username, then generate the key. Copy it immediately and open Telegram using the handoff link." }, { slug: "troubleshooting", title: "Pairing troubleshooting", category: "Troubleshooting", excerpt: "Fix pending, failed, or disconnected pairing sessions.", content: "Confirm your phone number includes the country code. Keep the Pterodactyl worker running, avoid repeated requests, and retry after a failed session." }, { slug: "commands", title: "Bot command reference", category: "Commands", excerpt: "Browse commands for moderation, media, AI, and utilities.", content: "Admin: .kick @user, .warn @user. Media: .play song name. AI: .ask your question. Utilities: .ping and .menu." }, { slug: "faq", title: "Frequently asked questions", category: "FAQ", excerpt: "Answers about pairing, keys, panels, renewals, and support.", content: "Pairing is intended to persist while the bot remains connected. Keys have fixed expiration dates. Panel orders move from Pending to Approved to Provisioned after review." }];

export default function Docs() {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("All"); const [selected, setSelected] = useState("pairing-guide");
  const { data } = trpc.catalog.docs.useQuery({ query: query || undefined });
  const docs = data?.length ? data : fallbackDocs;
  const categories = ["All", ...Array.from(new Set(docs.map((doc) => doc.category)))];
  const filtered = useMemo(() => docs.filter((doc) => category === "All" || doc.category === category), [docs, category]);
  const article = filtered.find((doc) => doc.slug === selected) ?? filtered[0] ?? docs[0];
  return <div className="docs-shell"><header className="topbar"><Link href="/" className="brand"><span className="brand-mark"><Zap size={16} /></span><span>BLACKLORD <em>DOCS</em></span></Link><div className="docs-header-links"><Link href="/dashboard" className="text-link">Dashboard <ChevronRight size={14} /></Link><Link href="/support" className="text-link">Support <ChevronRight size={14} /></Link></div></header><main className="docs-main"><div className="docs-intro"><Link href="/" className="back-link"><ArrowLeft size={14} /> Back to platform</Link><div className="eyebrow">KNOWLEDGE CENTER</div><h1>Everything you need to run your bots.</h1><p>Setup guides, command references, troubleshooting notes, and answers for every stage of the Blacklord workflow.</p><div className="docs-search"><Search size={17} /><input placeholder="Search guides, commands, and questions" value={query} onChange={(e) => setQuery(e.target.value)} /></div></div><div className="docs-layout"><aside className="docs-sidebar"><div className="field-label">Browse by category</div>{categories.map((item) => <button className={category === item ? "doc-category active" : "doc-category"} key={item} onClick={() => setCategory(item)}>{item === "Commands" ? <Command size={15} /> : item === "Troubleshooting" ? <Wrench size={15} /> : item === "FAQ" ? <ShieldQuestion size={15} /> : <BookOpen size={15} />}{item}<span>{item === "All" ? docs.length : docs.filter((doc) => doc.category === item).length}</span></button>)}<div className="docs-tip"><strong>Need help?</strong><p>Include your pairing ID, bot name, and phone number when opening a support ticket.</p><Link href="/support" className="text-link">Open ticket <ChevronRight size={14} /></Link></div></aside><section className="docs-list">{filtered.map((doc) => <button className={article?.slug === doc.slug ? "doc-card active" : "doc-card"} key={doc.slug} onClick={() => setSelected(doc.slug)}><span className="doc-card-icon"><BookOpen size={16} /></span><div><small>{doc.category}</small><h3>{doc.title}</h3><p>{doc.excerpt}</p></div><ChevronRight size={16} /></button>)}</section><article className="doc-article"><div className="eyebrow">{article?.category ?? "Guide"}</div><h2>{article?.title ?? "Choose a guide"}</h2><p className="article-intro">{article?.excerpt}</p><div className="article-copy"><p>{article?.content}</p><h3>Recommended next steps</h3><ul><li>Keep your bot worker online while requests are processing.</li><li>Use the dashboard to review statuses, keys, orders, and activity.</li><li>Open support with context if a status remains unresolved.</li></ul></div><Link href="/support" className="primary-button">Talk to support <ChevronRight size={14} /></Link></article></div></main></div>;
}
