import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { ArrowRight, Bot, Check, ChevronRight, Copy, KeyRound, LifeBuoy, Menu, Play, Server, ShieldCheck, Wallet, X, Zap } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

const steps = ["Waiting", "Code Generated", "Connected"];
const fallbackBots = ["BLACKLORD XMD", "SAMSUNG XMD", "TALKLESS ULTRA", "SKYLAR XMD", "RITA XMD"];

export default function Home() {
  const { isAuthenticated } = useAuth();
  const { data: bots = [] } = trpc.catalog.bots.useQuery();
  const { data: plans = [] } = trpc.catalog.plans.useQuery();
  const createPairing = trpc.pairing.create.useMutation();
  const [pairingId, setPairingId] = useState(0);
  const pairingInput = useMemo(() => ({ id: pairingId }), [pairingId]);
  const pairingStatusQuery = trpc.pairing.status.useQuery(pairingInput, { enabled: pairingId > 0, refetchInterval: pairingId > 0 ? 2500 : false });
  const generateKey = trpc.keys.generate.useMutation();
  const redeemVoucher = trpc.wallet.redeem.useMutation();
  const [mobileOpen, setMobileOpen] = useState(false); const [selectedBot, setSelectedBot] = useState("blacklord-xmd"); const [phone, setPhone] = useState(""); const [pairStatus, setPairStatus] = useState(0); const [pairCode, setPairCode] = useState(""); const [telegramUser, setTelegramUser] = useState(""); const [duration, setDuration] = useState("30"); const [voucher, setVoucher] = useState(""); const [copied, setCopied] = useState(false);
  const botList = bots.length ? bots : fallbackBots.map((name, i) => ({ id: i + 1, slug: name.toLowerCase().replaceAll(" ", "-"), name, vendor: "BLACKLORD TECH INC", description: "Reliable automation for your WhatsApp community.", capabilities: "Groups • media • utilities", status: "online" }));
  const planList = plans.length ? plans : [{ id: 1, name: "10GB Storage", tier: "Starter", description: "1GB RAM, 10GB disk, 40% CPU for small bots.", priceSd: "10.00", specs: "1GB RAM • 10GB disk" }, { id: 2, name: "Bulky 2", tier: "Power User", description: "Multi-bot hosting with generous resources.", priceSd: "20.00", specs: "Multi-bot • Priority support" }, { id: 3, name: "Bulky 3", tier: "Enterprise", description: "High performance for growing communities.", priceSd: "40.00", specs: "Monitoring • High performance" }, { id: 4, name: "Bulky 4", tier: "Extreme", description: "Professional automation resources.", priceSd: "60.00", specs: "Dedicated resources • Alerts" }, { id: 5, name: "Unlimited Admin", tier: "Full Control", description: "Full panel admin access.", priceSd: "100.00", specs: "Admin access • Unlimited" }];
  const currentBot = useMemo(() => botList.find((bot) => bot.slug === selectedBot) ?? botList[0], [botList, selectedBot]);
  const requireLogin = () => { if (!isAuthenticated) { startLogin(); return false; } return true; };
  useEffect(() => { const status = pairingStatusQuery.data?.status; if (status === "waiting") setPairStatus(0); if (status === "code_generated") setPairStatus(1); if (status === "connected") setPairStatus(2); if (status === "failed" || status === "disconnected") setPairStatus(3); }, [pairingStatusQuery.data?.status]);
  const pair = async () => { if (!phone) return toast.error("Enter a WhatsApp number with country code."); if (!requireLogin()) return; try { const result = await createPairing.mutateAsync({ botSlug: selectedBot, phoneNumber: phone }); setPairingId(Number(result.id)); setPairCode(result.pairingCode); setPairStatus(1); toast.success("Pairing code generated. Waiting for WhatsApp confirmation."); } catch { setPairStatus(3); toast.error("Pairing request failed. Try again or open support."); } };
  const makeKey = async () => { if (!requireLogin()) return; try { const result = await generateKey.mutateAsync({ botSlug: selectedBot, telegramUsername: telegramUser || undefined, durationDays: Number(duration) as 7 | 30 | 90 | 365 }); await navigator.clipboard.writeText(result.keyValue); setCopied(true); toast.success("Key generated and copied."); } catch { toast.error("Sign in to generate a key."); } };
  const redeem = async () => { if (!requireLogin()) return; if (!voucher) return toast.error("Enter a voucher code."); try { const result = await redeemVoucher.mutateAsync({ code: voucher }); toast.success(`${result.message} +${result.amount} SD`); setVoucher(""); } catch { toast.error("Voucher is invalid or already redeemed."); } };

  return <div className="site-shell"><header className="topbar"><Link href="/" className="brand"><span className="brand-mark"><Zap size={16} /></span><span>BLACKLORD <em>TECH INC</em></span></Link><nav className={mobileOpen ? "nav nav-open" : "nav"}><a href="#pair">Pairing</a><a href="#plans">Plans</a><Link href="/docs">Docs</Link><Link href="/support">Support</Link><Link href="/dashboard">Dashboard</Link></nav><div className="top-actions"><Button className="ghost-button" onClick={() => isAuthenticated ? window.location.assign("/dashboard") : startLogin()}>{isAuthenticated ? "Open dashboard" : "Sign in"}</Button><button className="menu-button" onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header><main>
  <section className="hero section-grid"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot" /> WHATSAPP BOT OPERATIONS</div><h1>Pair, monitor, and grow your <span>automation stack.</span></h1><p className="hero-lede">A single command center for WhatsApp pairing, Telegram keys, panel hosting, wallet credits, and bot health.</p><div className="hero-actions"><Button className="primary-button" onClick={() => document.getElementById("pair")?.scrollIntoView({ behavior: "smooth" })}>Start pairing <ArrowRight size={16} /></Button><Link href="/docs" className="text-link">Read the docs <ChevronRight size={15} /></Link></div><div className="hero-trust"><ShieldCheck size={16} /> Secure account flows <span>•</span> Real-time status <span>•</span> 5 bot profiles</div></div><div className="hero-visual"><div className="orb orb-one" /><div className="orb orb-two" /><div className="terminal-card"><div className="terminal-head"><span /><span /><span /><small>pairing://live</small></div><div className="terminal-body"><p><span className="green">$</span> blacklord pair --bot {currentBot?.slug ?? "blacklord-xmd"}</p><p className="muted">initializing secure bridge...</p><p><span className="green">✓</span> session request accepted</p><p><span className="gold">→</span> code <strong>{pairCode || "BL-7K4QZ"}</strong></p><div className="terminal-progress"><span /></div><p className="muted">waiting for WhatsApp confirmation</p></div></div><div className="floating-stat"><span className="status-dot" /> <strong>7</strong><small>active bots</small></div></div></section>
  <section className="metrics"><div><strong>5</strong><span>Bot profiles</span></div><div><strong>99.9%</strong><span>Bridge target</span></div><div><strong>&lt;60s</strong><span>Typical pairing</span></div><div><strong>24/7</strong><span>Support workflow</span></div></section>
  <section id="pair" className="section-block"><div className="section-heading"><div><div className="eyebrow">01 / CONNECT</div><h2>Pair your WhatsApp number</h2><p>Choose a bot, enter your number, and follow the live status tracker.</p></div><div className="step-pill"><span className="status-dot" /> {pairStatus === 0 ? "Ready to start" : pairStatus === 3 ? "Pairing failed" : steps[Math.min(pairStatus, 2)]}</div></div><div className="pair-layout"><div className="panel-card pairing-card"><div className="field-label">Choose bot profile</div><div className="bot-tabs">{botList.map((bot) => <button key={bot.slug} className={selectedBot === bot.slug ? "bot-tab active" : "bot-tab"} onClick={() => setSelectedBot(bot.slug)}><Bot size={15} /><span>{bot.name}</span></button>)}</div><div className="field-label">WhatsApp number</div><div className="input-row"><input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="e.g. 254712345678" type="tel" /><Button className="primary-button" onClick={pair}>{createPairing.isPending ? "Working…" : "Get pairing code"}</Button></div>{pairCode && <div className="code-banner"><div><small>PAIRING CODE</small><strong>{pairCode}</strong></div><Button className="outline-button" onClick={() => { navigator.clipboard.writeText(pairCode); toast.success("Code copied."); }}><Copy size={14} /> Copy</Button></div>}<div className="status-tracker">{steps.map((label, index) => <div key={label} className={pairStatus >= index && pairStatus !== 3 ? "status-step done" : "status-step"}><span>{pairStatus > index && pairStatus !== 3 ? <Check size={13} /> : index + 1}</span><small>{label}</small></div>)}</div></div><div className="panel-card how-card"><div className="card-icon"><Play size={18} /></div><h3>How onboarding works</h3><p>Keep your bot worker running while the request is pending. When WhatsApp accepts the code, your dashboard changes to Connected.</p><div className="mini-list"><div><b>01</b><span>Enter your international number</span></div><div><b>02</b><span>Request and copy the code</span></div><div><b>03</b><span>Confirm from WhatsApp Linked Devices</span></div></div><Link href="/docs" className="text-link">Open pairing guide <ArrowRight size={14} /></Link></div></div></section>
  <section className="section-block dark-band"><div className="section-heading"><div><div className="eyebrow">02 / KEY ACCESS</div><h2>Generate a Telegram key</h2><p>Time-limited access with a clear expiry date and instant copy.</p></div><div className="card-icon"><KeyRound size={18} /></div></div><div className="key-form panel-card"><div className="form-grid"><label>Bot<select value={selectedBot} onChange={(e) => setSelectedBot(e.target.value)}>{botList.map((bot) => <option value={bot.slug} key={bot.slug}>{bot.name}</option>)}</select></label><label>Telegram username <span>(optional)</span><input value={telegramUser} onChange={(e) => setTelegramUser(e.target.value)} placeholder="@yourusername" /></label><label>Duration<select value={duration} onChange={(e) => setDuration(e.target.value)}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option><option value="365">365 days</option></select></label></div><div className="form-submit"><Button className="primary-button" onClick={makeKey}><KeyRound size={15} /> {copied ? "Key copied" : "Generate key"}</Button><span>Keys appear in your dashboard after generation.</span></div></div></section>
  <section id="plans" className="section-block"><div className="section-heading"><div><div className="eyebrow">03 / HOSTING</div><h2>Panel plans for every stage</h2><p>Use SD balance to request Pterodactyl hosting and track provisioning status.</p></div><Link href="/dashboard" className="text-link">View orders <ArrowRight size={14} /></Link></div><div className="plan-grid">{planList.map((plan, index) => <div className={index === 4 ? "plan-card featured" : "plan-card"} key={plan.id}><div className="plan-top"><span className="plan-number">0{index + 1}</span><span className="plan-tier">{plan.tier}</span></div><h3>{plan.name}</h3><p>{plan.description}</p><div className="plan-price"><strong>{plan.priceSd}</strong><span>SD</span></div><div className="plan-spec">{plan.specs}</div><Button className="outline-button" onClick={() => { if (!requireLogin()) return; toast.success("Checkout started. Complete the order from your dashboard."); }}>Get this plan <ArrowRight size={14} /></Button></div>)}</div></section>
  <section className="section-block wallet-section"><div className="wallet-copy"><div className="eyebrow">04 / WALLET</div><h2>Redeem credits. Keep moving.</h2><p>Voucher credits flow into your SD wallet, with every redemption and purchase visible in transaction history.</p><div className="feature-row"><span><Wallet size={16} /></span><div><strong>Wallet history</strong><small>Credits, keys, panels, and referral rewards.</small></div></div><div className="feature-row"><span><Server size={16} /></span><div><strong>Order tracking</strong><small>Pending → Approved → Provisioned.</small></div></div></div><div className="panel-card voucher-card"><div className="card-icon"><Wallet size={18} /></div><h3>Redeem a voucher</h3><p>Enter your code to credit your SD balance.</p><div className="input-row"><input value={voucher} onChange={(e) => setVoucher(e.target.value)} placeholder="VOUCHER-XXXX" /><Button className="primary-button" onClick={redeem}>Redeem</Button></div><small>Sign in to save the credit to your wallet.</small></div></section>
  <section className="section-block bot-section"><div className="section-heading"><div><div className="eyebrow">05 / BOT LIBRARY</div><h2>Choose the right engine</h2><p>Every profile has a clear purpose, capability set, and status.</p></div></div><div className="library-grid">{botList.map((bot) => <div className="library-card" key={bot.slug}><div className="library-head"><span className="bot-avatar"><Bot size={17} /></span><span className="online-label"><span className="status-dot" /> {bot.status ?? "online"}</span></div><h3>{bot.name}</h3><small>{bot.vendor}</small><p>{bot.description}</p><div className="capability-line">{bot.capabilities}</div></div>)}</div></section>
  <section className="cta-section"><div><div className="eyebrow">NEED A HAND?</div><h2>Build with confidence.</h2><p>Use the docs for setup guides, commands, and troubleshooting—or open a support ticket with your pairing context attached.</p></div><div className="cta-actions"><Link href="/docs" className="primary-button">Browse docs <ArrowRight size={15} /></Link><Link href="/support" className="outline-button">Open support <LifeBuoy size={15} /></Link></div></section>
 </main><footer className="footer"><span>© 2026 BLACKLORD TECH INC</span><span>Secure pairing • Managed hosting • Human support</span></footer></div>;
}
